version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - collage_static_volume:/collage/static
      - collage_media_volume:/collage/media
    networks:
      - nginx_network

volumes:
  collage_static_volume:
    external: true
  collage_media_volume:
    external: true
networks:
  nginx_network:
    external: true