# Generated by Django 3.1.7 on 2021-03-30 10:00

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_auto_20210330_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')], default=1, verbose_name='وضعیت')),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelAlbum', to='accounts.realstatemodel', verbose_name='مربوط به املاک ')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': 'آلبوم',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='a', verbose_name='تصویر اصلی')),
                ('create_time', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesA', to='content.imagealbummodel', verbose_name='مربوط به آلبوم')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='hotspotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.SmallIntegerField(default=0, verbose_name='مختصات افقی')),
                ('y', models.SmallIntegerField(default=0, verbose_name='مختصات عمودی')),
                ('z', models.SmallIntegerField(default=0, verbose_name='مختصات عمقی')),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagehotspot', to='content.imagemodel', verbose_name='هات اسپات برای ')),
            ],
        ),
    ]
